apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi.fullname" . }}
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | int }}
      targetPort: {{ .Values.service.targetPort | int }}
  selector:
    app.kubernetes.io/name: {{ include "fastapi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}