apiVersion: v1
entries:
  fastapi-helm-chart:
  - annotations:
      artifacthub.io/changes: '- initial release'
      artifacthub.io/license: MIT
      artifacthub.io/provider: anqorithm
      artifacthub.io/readme_url: https://github.com/anqorithm/fastapi-helm-chart/blob/main/README.md
      artifacthub.io/tags: fastapi, helm, api, kubernetes
      category: Backend
    apiVersion: v2
    appVersion: 0.0.3
    created: "2025-02-14T21:09:15.9810273+03:00"
    description: A Helm chart for deploying a FastAPI application
    digest: 8baad8526a6238e64b898788ccb60361abb95aa104c11fb1ab423eedd187ac86
    home: https://github.com/anqorithm/fastapi-helm-chart
    keywords:
    - fastapi
    - helm
    - api
    - kubernetes
    maintainers:
    - email: anqorithm@protonmail.com
      name: Abdullah Alqahtani
    name: fastapi-helm-chart
    sources:
    - https://github.com/anqorithm/fastapi-helm-chart
    type: application
    urls:
    - https://anqorithm.github.io/fastapi-helm-chart/fastapi-helm-chart-0.0.3.tgz
    version: 0.0.3
  - annotations:
      artifacthub.io/changes: '- initial release'
      artifacthub.io/license: MIT
      artifacthub.io/provider: anqorithm
      artifacthub.io/readme_url: https://github.com/anqorithm/fastapi-helm-chart/blob/main/README.md
      artifacthub.io/tags: fastapi, helm, api, kubernetes
      category: Backend
    apiVersion: v2
    appVersion: 0.0.2
    created: "2025-02-14T21:09:15.9805083+03:00"
    description: A Helm chart for deploying a FastAPI application
    digest: 416b0915af58ff1fd7c99b5137caeb1d054a5aaa6e7699f81d6db9f2f1fc77aa
    home: https://github.com/anqorithm/fastapi-helm-chart
    keywords:
    - fastapi
    - helm
    - api
    - kubernetes
    maintainers:
    - email: anqorithm@protonmail.com
      name: Abdullah Alqahtani
    name: fastapi-helm-chart
    sources:
    - https://github.com/anqorithm/fastapi-helm-chart
    type: application
    urls:
    - https://anqorithm.github.io/fastapi-helm-chart/fastapi-helm-chart-0.0.2.tgz
    version: 0.0.2
  - annotations:
      category: Backend
    apiVersion: v2
    appVersion: 0.0.1
    created: "2025-02-14T21:09:15.9791524+03:00"
    description: A Helm chart for deploying a FastAPI application
    digest: 199fc22b5a5c59ae99341936689ca8a524fe53ad31a62d84a07ee4979f939bbe
    home: https://github.com/anqorithm/fastapi-helm-chart
    keywords:
    - fastapi
    - helm
    - api
    - kubernetes
    maintainers:
    - email: anqorithm@protonmail.com
      name: Abdullah Alqahtani
    name: fastapi-helm-chart
    sources:
    - https://github.com/anqorithm/fastapi-helm-chart
    type: application
    urls:
    - https://anqorithm.github.io/fastapi-helm-chart/fastapi-helm-chart-0.0.1.tgz
    version: 0.0.1
generated: "2025-02-14T21:09:15.9748569+03:00"
